### PR TITLE
[io-chunks] PR fix for Issue #2

### PR DESCRIPTION
**Pull request by netzulo**
# Tests

- [x] **local** : *manual local using tox*
- [x] **CIs** : *all CIs configured must be PASSED to consider completed PR*

## Issues related

- [x] #2

### CODE REVIEW

**Comment by netzulo** [comment]
please, squash to one commit :'( sorry for spam at RST commits xDDDD

**Comment by netzulo** [comment]
well.. going to rebase from : https://github.com/Terseus/python-io-chunks/compare/master...tox

**Comment by Terseus** [comment]
Thanks for your PR!

Unfortunately I was working in the same feature and pushed it to master, if you want update your PR code and see if there's something you want to submit in it, or close it otherwise.

**Comment by netzulo** [comment]
to the future!  :)

**Pull request closed without merging**
